/* Stern-Brocot sequence
For this task, the Stern-Brocot sequence is to be generated by an algorithm similar to that employed in generating the Fibonacci sequence.

The first and second members of the sequence are both 1:
1, 1
Start by considering the second member of the sequence
Sum the considered member of the sequence and its precedent, (1 + 1) = 2, and append it to the end of the sequence:
1, 1, 2
Append the considered member of the sequence to the end of the sequence:
1, 1, 2, 1
Consider the next member of the series, (the third member i.e. 2)
GOTO 3
─── Expanding another loop we get: ───
Sum the considered member of the sequence and its precedent, (2 + 1) = 3, and append it to the end of the sequence:
1, 1, 2, 1, 3
Append the considered member of the sequence to the end of the sequence:
1, 1, 2, 1, 3, 2
Consider the next member of the series, (the fourth member i.e. 1)
Create a function that returns the position in the Stern-Brocot sequence at which  n
  is first encountered, where the sequence is generated with the method outlined above. Note that this sequence uses 1 based indexing. */

function sternBrocot(num) {
  let seq=[1,1];
  for(let i=1;i<50;i++){
    seq.push(seq[i]+seq[i-1]);
    seq.push(seq[i]);
  }
  console.log(seq);
  for(let i=1;i<50;i++){
    if(seq[i]==num){
      return i+1;
    }
  }
}
